# Generated by Django 5.2.8 on 2025-11-27 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='courses/'),
        ),
    ]
